# Generated by Django 2.1.1 on 2018-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=280)),
                ('presentation_link', models.URLField()),
                ('video_link', models.URLField(default='')),
                ('interview_link', models.URLField(default='')),
                ('conference_link', models.URLField(default='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
