# Generated by Django 2.2.24 on 2021-11-05 17:38

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('berin', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='_description_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='conference_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='interview_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
