# Generated by Django 2.2.24 on 2021-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berin', '0004_auto_20211105_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
    ]
