# Generated by Django 2.2.24 on 2021-11-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berin', '0005_auto_20211105_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projectcovers'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectimages')),
                ('short_description', models.CharField(blank=True, default='', max_length=140)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berin.Project')),
            ],
        ),
    ]
