# Generated by Django 2.2.24 on 2021-11-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berin', '0006_auto_20211105_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='project',
            name='html_extra',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='berin.Project'),
        ),
    ]
