# Generated by Django 2.2.24 on 2021-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berin', '0007_auto_20211112_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='html_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projectcovers', verbose_name='Capa'),
        ),
    ]
